spring:
  application:
    name: ecommerce
  datasource:
    url: jdbc:h2:mem:ecommerce
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect