CREATE TABLE IF NOT EXISTS prices (
    BRAND_ID INT,
    START_DATE TIMESTAMP,
    END_DATE TIMESTAMP,
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE DECIMAL(5,2),
    CURR VARCHAR(3),
    LAST_UPDATE TIMESTAMP,
    LAST_UPDATE_BY VARCHAR(255)
);

INSERT INTO prices (BRAND_ID, START_DATE, END_DATE, PRICE_LIST, PRODUCT_ID, PRIORITY, PRICE, CURR, LAST_UPDATE, LAST_UPDATE_BY)
SELECT * FROM CSVREAD('src/main/resources/prices.csv');